export const movieData = [
  {
    id: "1",
    title: "The call",
    image: "./images/Call.jpeg",
    year: "2020",
    category: "korean",
    IMDB: "7.1",
  },
  {
    id: "2",
    title: "Pilot",
    image: "./images/Pilot.jpeg",
    year: "2024",
    category: "korean",
    IMDB: "6.2",
  },
  {
    id: "3",
    title: "Wonderland",
    image: "./images/wonderland.jpeg",
    year: "2024",
    category: "korean",
    IMDB: "6.2",
  },
  {
    id: "4",
    title: "Xhuma",
    image: "./images/xhuma.jpeg",
    year: "2024",
    category: "korean",
    IMDB: "6.9",
  },
  {
    id: "5",
    title: "always",
    image: "./images/always.jpeg",
    year: "2011",
    category: "korean",
    IMDB: "7.7",
  },
  {
    id: "6",
    title: "Me Before You",
    image: "./images/meBeforeYou.jpeg",
    year: "2016",
    category: "english",
    IMDB: "7.4",
  },
  {
    id: "7",
    title: "Me Before You",
    image: "./images/meBeforeYou.jpeg",
    year: "2016",
    category: "english",
    IMDB: "7.4",
  },
  {
    id: "8",
    title: "The School for Good and Evil",
    image: "./images/school.jpeg",
    year: "2022",
    category: "english",
    IMDB: "5.9",
  },
  {
    id: "9",
    title: "Witch",
    image: "./images/witch.jpeg",
    year: "2022",
    category: "english",
    IMDB: "6.5",
  },
  {
    id: "10",
    title: "Cinderella",
    image: "./images/cinde.jpeg",
    year: "2022",
    category: "english",
    IMDB: "4.4",
  },
  {
    id: "11",
    title: "96",
    image: "./images/96.jpeg",
    year: "2018",
    category: "tamil",
    IMDB: "8.5",
  },
  {
    id: "12",
    title: "Vaashi",
    image: "./images/vaashi.jpeg",
    year: "2022",
    category: "tamil",
    IMDB: "6.4",
  },
  {
    id: "13",
    title: "Remo",
    image: "./images/remo.jpeg",
    year: "2016",
    category: "tamil",
    IMDB: "6",
  },
  {
    id: "14",
    title: "Amaran",
    image: "./images/amaran.jpeg",
    year: "2024",
    category: "tamil",
    IMDB: "8.2",
  },
  {
    id: "15",
    title: "Diya",
    image: "./images/diya.jpeg",
    year: "2018",
    category: "tamil",
    IMDB: "5.6",
  },
];
